name: 'Setup CouchDB'
description: 'Set up a CouchDB database as a single node.'
author: 'Alexander Lang'
branding:
  icon: 'database'
  color: 'red'
inputs:
  # See https://hub.docker.com/_/couchdb for supported versions
  # and further details on input environment variables
  couchdb version:
    description: 'Version of CouchDB to use.'
    required: false
    default: 'latest'
  couchdb user:
    description: 'Username name of the admin user.'
    required: false
  couchdb password:
    description: 'Password of the admin user.'
    required: false
outputs:
  couchdb-url:
    description: 'Base URL to make requests to CouchDB.'
runs:
  using: 'docker'
  image: 'Dockerfile'
